export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_ERROR = 'POST_LOGIN_ERROR';

export const POST_PRODUCT = 'POST_PRODUCT';
export const POST_PRODUCT_SUCCESS = 'POST_PRODUCT_SUCCESS';
export const POST_PRODUCT_ERROR = 'POST_PRODUCT_ERROR';

export const POST_PRODUCTDETAIL = 'POST_PRODUCTDETAIL';
export const POST_PRODUCTDETAIL_SUCCESS = 'POST_PRODUCTDETAIL_SUCCESS';
export const POST_PRODUCTDETAIL_ERROR = 'POST_PRODUCTDETAIL_ERROR';

export const POST_DASHBOARDPROJECT = 'POST_DASHBOARDPROJECT';
export const POST_DASHBOARDPROJECT_SUCCESS = 'POST_DASHBOARDPROJECT_SUCCESS';
export const POST_DASHBOARDPROJECT_ERROR = 'POST_DASHBOARDPROJECT_ERROR';

export const GET_KYTINHKHOAN = 'GET_KYTINHKHOAN';
export const GET_KYTINHKHOAN_SUCCESS = 'GET_KYTINHKHOAN_SUCCESS';
export const GET_KYTINHKHOAN_ERROR = 'GET_KYTINHKHOAN_ERROR';

export const GET_NAMTINHKHOAN = 'GET_NAMTINHKHOAN';
export const GET_NAMTINHKHOAN_SUCCESS = 'GET_NAMTINHKHOAN_SUCCESS';
export const GET_NAMTINHKHOAN_ERROR = 'GET_NAMTINHKHOAN_ERROR';

export const GET_DONVIBOPHAN = 'GET_DONVIBOPHAN';
export const GET_DONVIBOPHAN_SUCCESS = 'GET_DONVIBOPHAN_SUCCESS';
export const GET_DONVIBOPHAN_ERROR = 'GET_DONVIBOPHAN_ERROR';

export const GET_THONGTINCHITIETDUAN = 'GET_THONGTINCHITIETDUAN';
export const GET_THONGTINCHITIETDUAN_SUCCESS = 'GET_THONGTINCHITIETDUAN_SUCCESS';
export const GET_THONGTINCHITIETDUAN_ERROR = 'GET_THONGTINCHITIETDUAN_ERROR';
 
