const images = {
  loginIcon2: require('./loginIcon_2.png'),
  menu_alt_03: require('./menu_alt_03.png'),
  Vector: require('./Vector.png'),
  Rectangle: require('./Rectangle.png'),
  Rectangle2: require('./Rectangle2.png'),
  Rectangle3: require('./Rectangle3.png'),
  Rectangle4: require('./Rectangle4.png'),
  Rectangle5: require('./Rectangle5.png'),
  Rectangle6: require('./Rectangle6.png'),
  Rectangle7: require('./Rectangle7.png'),
  Rectangle8: require('./Rectangle8.png'),
  icons_projt: require('./icons_projt.png'),
  Rectangle_209: require('./Rectangle_209.png'),
  ic_users: require('./icon_users.png'),
  icon_Home: require('./icon_Home.png'),
  ic_project: require('./ic_project.png'),
  ic_clock: require('./ic_clock.png'),
  ic_logout23: require('./ic_logout23.png'),
  Arrow: require('./Arrow.png'),
  dot1: require('./dot1.png'),
  dot2: require('./dot2.png'),
  dot5: require('./dot5.png'),
  dot7: require('./dot7.png'),
  business: require('./ic_bussiness.png'),
  dot_price_1: require('./dot_color_1.png'),
  dot_price_2: require('./dot_price_2.png'),
  dot_price_3: require('./dot_price_3.png'),
  buttum1: require('./buttomTouch_1.png'),
  buttum2: require('./buttumTouch_2.png'),
  ic_bag: require('./ic_bag.png'),
  ic_bag_2: require('./ic_bag_2.png'),
  bgrLogin: require('./bgr_login.png'),
  themis: require('./themis.png'),
  clearTxtInput: require('./clearTxtInput.png'),

  rectangleGreen: require('./RectangleGreen.png'),
  rectangleOrange: require('./RectangleOrange.png'),

  incomeBlue: require('./incomeBlue.png'),
  incomeOrange: require('./incomeOrange.png'),
  incomeGreen: require('./incomeGreen.png'),
  payment: require('./payment.png'),

  menuHeader: require('./ic_menuHeader.png'),
  themis: require('./themis.png'),
  // rightHeader: require('./ic_rightHeader.png'),

  bgrLogin: require('./bgr_login.png'),

  clearTxtInput: require('./clearTxtInput.png'),

  picJoined: require('./picJoined.png'),
  picRevenue: require('./picRevenue.png'),

  imgUp: require('./up.png'),
  imgDown: require('./down.png'),

  check: require('./check.png'),
  rightHeader: require('./ic_rightHeader.png'),
  back: require('./back.png'),
  dot_pr1: require('./dot_pr.png'),
  dot_pro2: require('./dot_pr2.png'),
  dot_pro3: require('./dot_pr3.png'),
  dot_pro5: require('./dot_pro5.png'),
  newimage1: require('./newimage1.png'),
  newimage2: require('./newimage2.png'),
  newimage3: require('./newimage3.png'),
  newimage4: require('./newimage4.png'),
  dot_blue1: require('./dot_blue1.png'),
  dot_blue2: require('./dot_blue2.png'),
  heart: require('./heart.png'),
  medal: require('./medal.png'),
  amima: require('./anima.png'),
  heardblue: require('./heardblue.png'),
  ic_fpt_is: require('./ic_fpt_is.png'),
  heardblue: require('./heardblue.png')
};
export default images;
