export default apiSanXuat = [
  {
    error_code: 'SUCCESSFUL',
    error_message: '',
    data: {
      List: [
        {
          List: [
            {
              ChiTra: 1,
              DonVi: 'FIS GMC',
              AccMail: 'GIANGLH3',
              FISX: 763,
              CongViecHoanThanhHieuQua: 7,
              TinhDungHanThoiGian: 8,
              MaNhanVien: '00088226',
              DiemThuongCaNhan: 0.66309,
              BoPhan: 'PB GMCeGOV',
              HoTenNhanVien: 'Lê Hương Giang',
              Thang: 'Thang 3.2020',
              ThuNhapConDuocTra: 0,
              GhiChu: 'FIS GMC',
              id: 46704,
              KPerformance: 8,
              HeSoTrachNhiem: 1,
              KhoiLuongCongViec: 0,
              DuLieuChiTra: 1666666.66667,
              MMSuDung: 0.051803887,
              RateNhanCong: 1.6,
              HeSoChiTra: 1,
              TenDuAn: 'GMC_EGOV_4_0',
              SoApproved: 21,
              MaDuAn: 'GMC_EGOV_4_0',
              SoLuongCungDaChiTra: 9545454.45,
              LoaiChiTra: 'milestone',
              NgayTinh: '15/01/2021',
              MilestoneKhoan: 'GMC_EGOV_4_0 (all ML trong kỳ)',
              ThuNhapTheoMLTraCuoiDA: 0,
              SoDeNghiTra: 1280138.48536,
              SoDaChiThuongDGTruoc: 0,
              ThaiDoHopTac: 9,
              ThuNhapChiTraDotNay: 0,
              KyTinhKhoan: '24',
            },
          ],
          info: {
            tenDuAn: 'GMC_EGOV_4_0',
            maDuAn: 'GMC_EGOV_4_0',
            duLieuChiTra: 5000000.00001,
          },
        },
      ],
      moreInfo: {
        SoDA: 4,
      },
    },
  },
];
